[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F"]

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = "src"
python_files = "test_*.py"
log_cli = true
log_cli_level = "INFO"